apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- configmap.yaml
- secret.yaml
- hpa.yaml
- ingress.yaml

images:
- name: nginx
  newName: 472634532065.dkr.ecr.us-east-1.amazonaws.com/lks/loadsim
  newTag: latest

commonLabels:
  app: lks-irs
  environment: monitoring 