apiVersion: v1
kind: Secret
metadata:
  name: lks-irs-secret
  namespace: monitoring
  labels:
    app: lks-irs
    environment: monitoring
type: Opaque
data:
  VITE_AWS_ACCESS_KEY_ID: "QVNJQVc0Q1pXVURRV0VENkZOV1U="
  VITE_AWS_SECRET_ACCESS_KEY: "VW5qU1dGV1daNkZLOHlOd3hKSEVLV2tBWDdmaHZadll2ZDFZNGV5Vw=="
  VITE_AWS_SESSION_TOKEN: "SVFvSmIzSnBaMmx1WDJWakVCOGFDWFZ6TFhkbGMzUXRNaUpHTUVRQ0lBOXVwWFIwb0hIdkhQVkpiczA3Tmx5bUdyQnlnWHc1UHY5UG1ENGc1cE5wQWlBd09jUU96Wmt4NFhTeFA1WE5SR1RLUmNITlRWVlpzVGFUOFFSbmtITng3eXFtQWdoSUVBSWFERFEzTWpZek5EVXpNakEyTlNJTVZydERYaHRXdDZVdFpwcTJLb01DSEdueWw2VHdYNEo1bkpRQTRkUmtKOUdabW5jNEVWSllRLzNrLy9hTkNIMzY1Y041eEovWnNDMWRhdXFuSVU5aGU5VDNBRmVQL09xMWlDRnorckdOQ0hyZTNxdnZjZ0pXN0JBWFhYbncrbVhIZ2ZDelh5VzNOV2QvQjdpZXFWRVg5eTZnQnl1cVJOeWhHeFNkMUFweVBRWXZ3Rm5Rc0VpSnQ5MWpTZm1WR0h3MmsxU05HczdTSk1WR2FjVUZsTnpsM1JwYUpqcVY5a2pXenVqZUUyOEIvNjV5cUpUaHljQVhkbk1BY3U4ajdkWnhMNFFDQ3NRaE0vcVExSWFLQ2Vla01pcDRaVGV2Ui94ZmQzaVBQSEhnbUFKOC9nVVVIV0RNZUJmTk9hWnR0cUUyS1gwSW5yb3FPbktXQ1F1Z2hZWHBDMmpkd0NpeFVrb0JGeTFRMitUREQvMzBsakNTcUk3RUJqcWVBVm9aellBTnI4bVFEZjRjTkN1bnlQU2NNMlh4Z3Y3cGV1TnE0VzY1N3o5UjJxQXhWNitpbUpPRmkvZEUyL2Z6Y0ZvelBSa0FxY2ljNThwckF6WDkwKzVvblFNVENadENOaUQ3NkVNTUxrZXRjWU1Td0d6enhSbCs4T2RPSGhDNlNaWTVBeVFET0YxSGU1N2Y2Y0ZtaWphSE5aNTZ5cVBScWxNaW52bk90VEwxRm5sTE13b1ZNOVZZZ2dGRjk5MUtLS2xoNVNteXB3R0tLOG5HbVpzTg=="