apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- hpa.yaml
- ingress.yaml
- ingressclass-alb.yaml
- ingressclassparams-alb.yaml
- configmap.yaml

labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app: lks-apps
      environment: apps 