apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: lks-apps-stage-hpa
spec:
  scaleTargetRef:
    name: lks-apps-stage
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80 