apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging
namePrefix: lks-apps-stage-

resources:
- ../../base

configMapGenerator:
  - name: loadsim-config
    literals:
      - CPU_LOAD_PERCENT=50
      - MEMORY_MB=256
      - DURATION_SEC=0
      - CRASH=false
      - CRASH_AFTER_TIME_MS=10
      - SHUTDOWN=false
      - SHUTDOWN_AFTER_TIME_MS=10

images:
- name: betuah/loadsim
  newName: betuah/loadsim
  newTag: latest

patchesStrategicMerge:
- deployment-patch.yaml
- hpa-patch.yaml
- ingress-patch.yaml 