apiVersion: v1
kind: ConfigMap
metadata:
  name: lks-irs-fe-config
  namespace: monitoring
  labels:
    app: lks-irs-fe
    environment: monitoring
data:
  VITE_API_BASE_URL: "http://k8s-monitori-lksirsin-369fb2a3ec-1263901323.us-east-1.elb.amazonaws.com/api"