apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: lks-irs-fe-hpa
  namespace: monitoring
  labels:
    app: lks-irs-fe
    environment: monitoring
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: lks-irs-fe
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80 