apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: lks-apps-prod-hpa
spec:
  scaleTargetRef:
    name: lks-apps-prod-loadsim-app
    kind: Deployment
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70 