apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production
namePrefix: lks-apps-prod-

resources:
- ../../base

configMapGenerator:
  - name: loadsim-config
    literals:
      - CPU_LOAD_PERCENT=50
      - MEMORY_MB=256
      - DURATION_SEC=0
      - CRASH=false
      - CRASH_AFTER_TIME_MS=10
      - SHUTDOWN=false
      - SHUTDOWN_AFTER_TIME_MS=10

images:
- name: betuah/loadsim
  newName: betuah/loadsim
  newTag: latest

patches:
- path: deployment-patch.yaml
  target:
    kind: Deployment
    name: loadsim-app
- path: hpa-patch.yaml
  target:
    kind: HorizontalPodAutoscaler
    name: loadsim-hpa
- path: ingress-patch.yaml
  target:
    kind: Ingress
    name: loadsim-ingress 