apiVersion: apps/v1
kind: Deployment
metadata:
  name: lks-irs-be
  namespace: monitoring
  labels:
    app: lks-irs-be
    environment: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lks-irs-be
  template:
    metadata:
      labels:
        app: lks-irs-be
        environment: monitoring
    spec:
      imagePullSecrets:
      - name: ecr-secret
      containers:
      - name: irs-be
        image: 472634532065.dkr.ecr.us-east-1.amazonaws.com/lks/irsbe:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: lks-irs-be-config
        - secretRef:
            name: lks-irs-be-secret
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 5