apiVersion: v1
kind: Secret
metadata:
  name: lks-irs-be-secret
  namespace: monitoring
  labels:
    app: lks-irs-be
    environment: monitoring
type: Opaque
data:
  # This is just support base64 encoded values
  # To encode: echo -n "your-value" | base64
  AWS_ACCESS_KEY_ID: "QVNJQVc0Q1pXVURRUlVOUElUN1M="
  AWS_SECRET_ACCESS_KEY: "allja2FOTkFPSWcrc1B1VnJFYXNoaUQ2NEhkWUtMSVlvWmdmOFovOQ=="
  AWS_SESSION_TOKEN: "SVFvSmIzSnBaMmx1WDJWakVEY2FDWFZ6TFhkbGMzUXRNaUpITUVVQ0lFNVh6WFJndmF4dGNYbjhiMk9sNUNlbGxsS3daWXkvWkloZDBlQ3hRRWl6QWlFQWtpQ3djamxzSUU4WW4vb3U0VVNCZ1VyV3Z5MXNjZmRQYlVJQzhiQlVDMk1xcGdJSVlCQUNHZ3cwTnpJMk16UTFNekl3TmpVaURJeTZoT3pFU3VnOWpvay9LQ3FEQXBPbVd0UThFMXVHd0lBd2MvVVQxQ3dJeGQzNE1BNmdZUTdMcWJZUmJ3ZUplZFdhMUhld1F2M3hLdmVvYmh1dExRcDVsZktrTFdPc2duTHBnLzh0WWM5TVNOZVhuekZqblpZSGdGd2w2NTlKUFNxV0dEU2xrK0FhM3Jaa3Q5QjUwUXFOQ1JNRmd2bTUwMy9PNXpOWkJJRHQzQWJUeDN2N2pNSzZHMWVxUFY1SjlKK0hBV0Nsa242cGp6SDFCdzN3MkZWYTdpZCtiaDZ5cHJuUExJMzlldnExTE9GNDNLVkNTUXJQRS8vV255dHFKQko0MUFyTkZ4SlR4aHA3aWM5N1p4cnJhNGZtUVNGTnE3ZFo1ZlJaa1dRMGU2V0lxcVlId3pnYWdSNmVmd1pCdGo0SnAxY1IwNzQ2SVpkcjRmVEZQWHorNVREcS9kREptcGMyS1RmdXBLbUZoMXN3cWVLVHhBWTZuUUVoK1lwREpWU1hVelAyZGFpS1lZV3Vid1c4ZTJocDZNYjRDeVhFdU5SZE1uMkRPaGM5OWc1N1J5dS9kYW9sV0loQzhBekIyemtxb1pLb3hYVEhBQWtZWktkUkpqS0o4ZGdsZVJsZGJ0RW5tNExMMUJiUWFBSnIzcDZwcDNxZWJRcnYxbjM0NXYzZ0FYTE9DbUErWHFWU3JqR0pRcnJFYXFaUDkzZGZNc0FEVWNOT0N5R2dzWWx0UnJVRDE3NEJhM251UitsY1BRK1FPTGVXa1VrMw=="